name: Build Android APK

on:
  push:
    branches: [ main ] 

permissions:
  contents: write 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install Dependencies
        run: npm install

      - name: Add Android Platform and Assets
        run: |
          npx cap add android
          npm install -D @capacitor/assets
          npx @capacitor/assets generate --android

      - name: Apply Custom Configurations
        run: |
          cp google-services.json android/app/ || true
          
          echo '<?xml version="1.0" encoding="utf-8"?><resources><string name="app_name">Monywissen</string><string name="title_activity_main">Monywissen</string><string name="server_client_id">987859318051-s78uq9pcqseg0u0hlren3tdqbpcrdav2.apps.googleusercontent.com</string></resources>' > android/app/src/main/res/values/strings.xml
          
          echo '<?xml version="1.0" encoding="utf-8"?>
          <resources>
              <style name="AppTheme" parent="Theme.AppCompat.Light.DarkActionBar">
                  <item name="colorPrimary">#1f6ddc</item>
                  <item name="colorPrimaryDark">#1f6ddc</item>
                  <item name="colorAccent">#1f6ddc</item>
              </style>
              
              <style name="AppTheme.NoActionBar" parent="Theme.AppCompat.Light.NoActionBar">
                  <item name="windowActionBar">false</item>
                  <item name="windowNoTitle">true</item>
                  
                  <item name="android:windowBackground">@android:color/white</item>
                  <item name="android:background">@null</item>
                  
                  <item name="android:statusBarColor">@android:color/transparent</item>
                  <item name="android:navigationBarColor">@android:color/transparent</item>
                  <item name="android:windowDrawsSystemBarBackgrounds">true</item>
                  <item name="android:windowLayoutInDisplayCutoutMode">shortEdges</item>
                  <item name="android:enforceStatusBarContrast">false</item>
                  <item name="android:enforceNavigationBarContrast">false</item>
                  
                  <item name="android:windowLightStatusBar">true</item>
                  <item name="android:windowLightNavigationBar">true</item>
                  <item name="android:datePickerDialogTheme">@android:style/Theme.DeviceDefault.Light.Dialog</item>
                  <item name="android:alertDialogTheme">@android:style/Theme.DeviceDefault.Light.Dialog.Alert</item>
              </style>

              <style name="AppTheme.NoActionBarLaunch" parent="AppTheme.NoActionBar">
                  <item name="android:background">@drawable/splash</item>
              </style>
          </resources>' > android/app/src/main/res/values/styles.xml

      - name: Sync Capacitor Project
        run: npx cap sync android

      - name: Inyectar Permisos Nativos de Android
        run: |
          echo "Añadiendo permisos de Cámara y Notificaciones al AndroidManifest.xml..."
          sed -i '/<\/manifest>/i \    <uses-permission android:name="android.permission.CAMERA" />' android/app/src/main/AndroidManifest.xml
          sed -i '/<\/manifest>/i \    <uses-feature android:name="android.hardware.camera" android:required="false" />' android/app/src/main/AndroidManifest.xml
          sed -i '/<\/manifest>/i \    <uses-permission android:name="android.permission.POST_NOTIFICATIONS" />' android/app/src/main/AndroidManifest.xml
          sed -i '/<\/manifest>/i \    <uses-permission android:name="android.permission.SCHEDULE_EXACT_ALARM" />' android/app/src/main/AndroidManifest.xml
          sed -i '/<\/manifest>/i \    <uses-permission android:name="android.permission.USE_EXACT_ALARM" />' android/app/src/main/AndroidManifest.xml

      - name: Build APK (Release)
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease

      - name: Sign APK
        run: |
          $ANDROID_HOME/build-tools/34.0.0/apksigner sign --ks monywissen-release.jks \
            --ks-key-alias "monywissen" \
            --ks-pass pass:"monywissen" \
            --key-pass pass:"monywissen" \
            android/app/build/outputs/apk/release/app-release-unsigned.apk
          
          mv android/app/build/outputs/apk/release/app-release-unsigned.apk android/app/build/outputs/apk/release/Monywissen-Signed.apk

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Monywissen-Produccion
          path: android/app/build/outputs/apk/release/Monywissen-Signed.apk
          retention-days: 7

      - name: Extraer versión del HTML
        id: get_version
        run: |
          VERSION=$(grep -oP '(?<=content=")[^"]*(?=")' <<< "$(grep 'meta name="app-version"' index.html)")
          echo "APP_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Crear o Actualizar Release en GitHub
        uses: ncipollo/release-action@v1
        with:
          artifacts: "android/app/build/outputs/apk/release/Monywissen-Signed.apk"
          tag: "vLatest"
          name: ${{ env.APP_VERSION }} # Aquí usamos la variable extraída
          body: "Actualización automática de Monywissen."
          allowUpdates: true
          replacesArtifacts: true
          token: ${{ secrets.GITHUB_TOKEN }}